### ISSUE TITLE
2 or more slack arguments results in invalid slack request

### ISSUE THREAD

**Issue by sounddroid** [gverni/validate-slack-request#1]
Hi! 

Thanks for the creating this module. I think I came across a small issue: 

In slack, if a user types `/command arg1` , your module is correct, it returns true.

However, if a user types `/command arg1 arg2` the module returns false although the request is valid.

**Comment by gverni** [comment]
@sounddroid thanks for reporting the issue! I'll have a look and get back to you...

**Comment by sounddroid** [comment]
@gverni thank you! 

Perhaps the issue is in this section

`const bodyPayload = querystring.stringify(httpReq.body)`

 `if (!(xSlackRequestTimeStamp && SlackSignature && bodyPayload)) {
    return false
  }`

Is it required to stringify the httpReq.body? I think the Slack documentation says to take the raw body?

**Comment by gverni** [comment]
Sorry @sounddroid I haven't had the time to work on the fix today. Regarding your suggestion, the `httpReq.body` is supposed to be an object (see more [here](https://expressjs.com/en/api.html#req.body)) so you need to _stringify_ it before using it. I remember something in slack documentation as to how to _serialize_ more than one argument. I need to check it again as soon as I have some more time. 

Stay tuned and thanks for your patience!

**Comment by sounddroid** [comment]
No problem @gverni . Thank you for your time. Yes, I remember that `req.body` defaults to undefined. Compared to AWS Lambda's `event.body` where the body comes in as a raw string. Let me know what you discover. I'm more than curious. Thanks again.

**Comment by gverni** [comment]
@sounddroid thanks for your patience and sorry if it took me a while (I had to set-up my Slack testing environment again). The problem turned out to be in the way my code is _forming_ the raw body (more info in the commit 3650ac0). There's probably a better way to achieve that, but it should work fine given the specific format of the Slack request.

**Comment by sounddroid** [comment]
@gverni Thank you! It is working as expected and handling > 1 Slack argument. Cheers!
