### ISSUE TITLE
Slack Interactive Components

### ISSUE THREAD

**Issue by sounddroid** [gverni/validate-slack-request#3]
Hi again! I think I found another issue:

If you have an "Interactive Component" endpoint setup at api.slack.com for your Slack app, any button or subsequent dialog submission (that reaches this endpoint) are considered **_invalid_** Slack requests.

I think it might be related to how you're parsing the request body. I tried to put your middleware as the first middleware in the Express stack but the issue persists. I also tried putting your middleware after the urlencoded middleware too but no luck. Any ideas?

Thanks again!

<img width="721" alt="Screen Shot 2019-06-30 at 8 31 50 AM" src="https://user-images.githubusercontent.com/26507486/60398840-afeffa00-9b11-11e9-9b34-83e2b816d4d1.png">

**Comment by sounddroid** [comment]
In fact, I think your module is ok. It might be an issue with how ngrok is transforming request bodies. I'll do more investigation.

**Comment by gverni** [comment]
Thanks @sounddroid for testing my module! Sure, keep me posted on what you find...

**Comment by sounddroid** [comment]
Hi @gverni 

Say a user clicks on an interactive button (on Slack) which then calls up a dialog box. After the user submits the dialog box (which delivers the payload to the "Interactive Components Request URL") this is where your module thinks it's an invalid request. 

My gut tells it's about how it's parsing the raw payload? Is there a way to enforce that the raw payload (before any Express middleware) is used when verifying the Slack request?

**Comment by gverni** [comment]
> My gut tells it's about how it's parsing the raw payload? Is there a way to enforce that the raw payload (before any Express middleware) is used when verifying the Slack request?

To keep the module as simple as possible, I made the decision to use the Express default body parser middleware (express documentation uses `express.urlencoded()`). As per the [documentation]() this contains "key-value pairs of data submitted in the request body". Unfortunately I wasn't able to find a way to extract the raw body, unless a different body parser middleware is used. Let me try to see if there is some other way to get the raw body without changing middleware. 

@sounddroid do you happen to have a sample of the raw body I can use for testing?

**Comment by sounddroid** [comment]
@gverni I will try my best to hunt down a sample of the raw body. I totally forgot that req.body is null before any middleware is applied. I will look as well.

**Comment by gverni** [comment]
Thank you @sounddroid. The alternative is to use something like [raw-body](https://www.npmjs.com/package/raw-body), but I'm reluctant to have additional dependencies either in this module or on express. I would prefer to find a way to get the raw body from what comes from express.

**Comment by sounddroid** [comment]
Hi @gverni ! While I don't have an example raw body, I do have some more data points for you. 

It appears that validate-slack-request returns `false` using these special characters:

```
/command !
/command ~
/command (
/command )
/command *
```
Perhaps it's the way Express is parsing the body?

**Comment by gverni** [comment]
Hey @sounddroid thanks for the update! I'm sorry I wasn't able to work on this yet. You are correct: the express parsing middleware is converting all the urlencoded characters to their ASCII one, hence we are having this issue. I may be able to fix that without adding dependencies. Let me have a look and get back to you...

**Comment by sounddroid** [comment]
Thanks so much @gverni ! Looking forward to it!

**Comment by gverni** [comment]
Hi @sounddroid, I pushed a new update (v0.1.3) that fix all the characters apart from `~`. I need a bit more time for this latter...

**Comment by gverni** [comment]
@sounddroid the fix for `~` is in version v0.1.4. Have a try and let me know. 

And thanks again for helping with this!!

**Comment by sounddroid** [comment]
@gverni Thanks so much! Yes all is working!!!
